### 客户端拿着资源拥有者的用户名、密码向授权服务器请求令牌（access_token）
POST http://localhost:53010/uaa/oauth/token
Content-Type: application/x-www-form-urlencoded

client_id=c1&client_secret=secret&grant_type=password&username=zhangsan&password=123

### 验证令牌使用
POST http://localhost:53010/uaa/oauth/check_token
Content-Type: application/x-www-form-urlencoded

token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzMSJdLCJ1c2VyX25hbWUiOiJ7XCJmdWxsbmFtZVwiOlwi5byg5LiJXCIsXCJpZFwiOlwiMVwiLFwibW9iaWxlXCI6XCIxMjM0NTZcIixcInBhc3N3b3JkXCI6XCIkMmEkMTAkYUZzT0Z6dWp0UENuVUNVS2NvenNIdXgwclEvM2ZhQUhHRlNWYjlZLkIxbnRwbUVoalJ0cnVcIixcInVzZXJuYW1lXCI6XCJ6aGFuZ3NhblwifSIsInNjb3BlIjpbIlJPTEVfQURNSU4iLCJST0xFX1VTRVIiLCJST0xFX0FQSSJdLCJleHAiOjE2MjkwMzkwNTUsImF1dGhvcml0aWVzIjpbInAxIiwicDMiXSwianRpIjoiMTY1Yzk4NjQtYzdkYi00NmVjLWE5MzktMTNlZTg0ZmEzZWQ2IiwiY2xpZW50X2lkIjoiYzEifQ.q4Am_fRuBvvmXyRYtcVI1MjEBm7Lbopuv1cVIoTnl2A

### 接口访问带令牌
GET http://localhost:53010/order/r1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzMSJdLCJ1c2VyX25hbWUiOiJ7XCJmdWxsbmFtZVwiOlwi5byg5LiJXCIsXCJpZFwiOlwiMVwiLFwibW9iaWxlXCI6XCIxMjM0NTZcIixcInBhc3N3b3JkXCI6XCIkMmEkMTAkYUZzT0Z6dWp0UENuVUNVS2NvenNIdXgwclEvM2ZhQUhHRlNWYjlZLkIxbnRwbUVoalJ0cnVcIixcInVzZXJuYW1lXCI6XCJ6aGFuZ3NhblwifSIsInNjb3BlIjpbIlJPTEVfQURNSU4iLCJST0xFX1VTRVIiLCJST0xFX0FQSSJdLCJleHAiOjE2MjkwMzkwNTUsImF1dGhvcml0aWVzIjpbInAxIiwicDMiXSwianRpIjoiMTY1Yzk4NjQtYzdkYi00NmVjLWE5MzktMTNlZTg0ZmEzZWQ2IiwiY2xpZW50X2lkIjoiYzEifQ.q4Am_fRuBvvmXyRYtcVI1MjEBm7Lbopuv1cVIoTnl2A
