### 验证令牌使用
POST http://localhost:53020/uaa/oauth/check_token
Content-Type: application/x-www-form-urlencoded

token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzMSJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbIlJPTEVfQURNSU4iLCJST0xFX1VTRVIiLCJST0xFX0FQSSJdLCJleHAiOjE2MjQ2MTQwMTEsImF1dGhvcml0aWVzIjpbInAxIiwicDMiXSwianRpIjoiMzA4OWU4MDUtNjE0OS00YzhlLTg4YjMtNGY4MTUwM2MzMzhlIiwiY2xpZW50X2lkIjoiYzEifQ.UBpJ89d2YNRyk72Pg5HD0ODZg7_tDCjljxakVh85ALI

### 接口访问带令牌
GET http://localhost:53021/order/r1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzMSJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2MjQ2MTAwNjAsImF1dGhvcml0aWVzIjpbInAxIiwicDMiXSwianRpIjoiMGI1ODViYzctMGRmMC00Y2YwLWJiZDktZTdmMjhjY2M3OTk2IiwiY2xpZW50X2lkIjoiYzEifQ.xHZPjzFP4A7nShlE-3bRH-_qSFOE-chkjGwe6Uc4y4k