### 验证令牌使用
POST http://localhost:53020/uaa/oauth/check_token
Content-Type: application/x-www-form-urlencoded

token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzMSJdLCJ1c2VyX25hbWUiOiJ7XCJmdWxsbmFtZVwiOlwi5byg5LiJXCIsXCJpZFwiOlwiMVwiLFwibW9iaWxlXCI6XCIxMjM0NTZcIixcInBhc3N3b3JkXCI6XCIkMmEkMTAkYUZzT0Z6dWp0UENuVUNVS2NvenNIdXgwclEvM2ZhQUhHRlNWYjlZLkIxbnRwbUVoalJ0cnVcIixcInVzZXJuYW1lXCI6XCJ6aGFuZ3NhblwifSIsInNjb3BlIjpbIlJPTEVfQURNSU4iLCJST0xFX1VTRVIiLCJST0xFX0FQSSJdLCJleHAiOjE2MjkwMjQ3MjksImF1dGhvcml0aWVzIjpbInAxIiwicDMiXSwianRpIjoiNTc3ZjRlYzMtNmQyZS00YmI0LWFjZWEtM2NiYWExN2RmOTI4IiwiY2xpZW50X2lkIjoiYzEifQ.VEqNzq927hxRmt1YF2NqPBjw11Cjxhrziz1yMV4IW3A

### 接口访问带令牌
GET http://localhost:53021/order/r1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzMSJdLCJ1c2VyX25hbWUiOiJ7XCJmdWxsbmFtZVwiOlwi5byg5LiJXCIsXCJpZFwiOlwiMVwiLFwibW9iaWxlXCI6XCIxMjM0NTZcIixcInBhc3N3b3JkXCI6XCIkMmEkMTAkYUZzT0Z6dWp0UENuVUNVS2NvenNIdXgwclEvM2ZhQUhHRlNWYjlZLkIxbnRwbUVoalJ0cnVcIixcInVzZXJuYW1lXCI6XCJ6aGFuZ3NhblwifSIsInNjb3BlIjpbIlJPTEVfQURNSU4iLCJST0xFX1VTRVIiLCJST0xFX0FQSSJdLCJleHAiOjE2MjkwMjM0NTAsImF1dGhvcml0aWVzIjpbInAxIiwicDMiXSwianRpIjoiMzg2ZWQ4YTEtOGNiZi00OTZmLWE3ZGYtMWVhYzA4YzY2MzEwIiwiY2xpZW50X2lkIjoiYzEifQ.CbaqoZgGTWl_ZKQEiPmCyBg-pNQ-d79eR5BEiz5hSqo