### 验证令牌使用
POST http://localhost:53020/uaa/oauth/check_token
Content-Type: application/x-www-form-urlencoded

token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzMSJdLCJ1c2VyX25hbWUiOiJ7XCJmdWxsbmFtZVwiOlwi5byg5LiJXCIsXCJpZFwiOlwiMVwiLFwibW9iaWxlXCI6XCIxMjM0NTZcIixcInBhc3N3b3JkXCI6XCIkMmEkMTAkYUZzT0Z6dWp0UENuVUNVS2NvenNIdXgwclEvM2ZhQUhHRlNWYjlZLkIxbnRwbUVoalJ0cnVcIixcInVzZXJuYW1lXCI6XCJ6aGFuZ3NhblwifSIsInNjb3BlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQVBJIl0sImV4cCI6MTYyOTAyOTc5NSwiYXV0aG9yaXRpZXMiOlsicDEiLCJwMyJdLCJqdGkiOiI4MmZiMWU2OS1mMWJkLTRlOTAtODViZi01OTdmZGI2NDA3MGMiLCJjbGllbnRfaWQiOiJjMSJ9.361ELip9BWJr7PYXug3z-Nt3hqmO9okIAWlcVMEkIYM

### 接口访问带令牌，注意此处对应客户端需要有 ROLE_ADMIN 权限，否则报 insufficient_scope
GET http://localhost:53021/order/r1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzMSJdLCJ1c2VyX25hbWUiOiJ7XCJmdWxsbmFtZVwiOlwi5byg5LiJXCIsXCJpZFwiOlwiMVwiLFwibW9iaWxlXCI6XCIxMjM0NTZcIixcInBhc3N3b3JkXCI6XCIkMmEkMTAkYUZzT0Z6dWp0UENuVUNVS2NvenNIdXgwclEvM2ZhQUhHRlNWYjlZLkIxbnRwbUVoalJ0cnVcIixcInVzZXJuYW1lXCI6XCJ6aGFuZ3NhblwifSIsInNjb3BlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQVBJIl0sImV4cCI6MTYyOTAyOTc5NSwiYXV0aG9yaXRpZXMiOlsicDEiLCJwMyJdLCJqdGkiOiI4MmZiMWU2OS1mMWJkLTRlOTAtODViZi01OTdmZGI2NDA3MGMiLCJjbGllbnRfaWQiOiJjMSJ9.361ELip9BWJr7PYXug3z-Nt3hqmO9okIAWlcVMEkIYM
